Lap 77
Lapin-Learn/frontend-web pull request #2
Opened 2024-08-10 17:01 UTC by Huy203

2024-08-11 04:45 UTC, NganTrucLe requested changes

2024-08-11 04:45 UTC, NganTrucLe commented on src/app/(auth)/confirm/page.tsx
page này có ý nghĩa gì á, t thấy có otp rùi

2024-08-11 04:45 UTC, NganTrucLe commented on src/app/(auth)/forget-password/page.tsx
> +  }
forgetPassword.mutate thui nha :"> cái toast dùng useToast(), và bỏ vô hook useForgetPassword() luôn á

2024-08-11 04:45 UTC, NganTrucLe commented on src/app/(auth)/forget-password/page.tsx
> +              className="w-full bg-primary"
hình như, đou cần `bg-primary` đâu

2024-08-11 04:45 UTC, NganTrucLe commented on src/app/(auth)/log-in/page.tsx
> +    .regex(/[0-9]/, "Password must contain at least one number"),
Gom chung thành 1 được khummm

2024-08-11 04:45 UTC, NganTrucLe commented on src/app/(auth)/log-in/page.tsx
>  import { toast } from "sonner";
![image](https://github.com/user-attachments/assets/5dab1d53-73e2-4808-b13e-718734ebe4f4)
fix eslint

2024-08-11 04:45 UTC, NganTrucLe commented on src/app/(auth)/log-in/page.tsx
>        password: "",
hình như nào cũm null thì bỏ đc á m

2024-08-11 04:45 UTC, NganTrucLe commented on src/app/(auth)/log-in/page.tsx
> +    console.log(result);
ờm dùng 1 convention thôi, thường t sẽ dùng `signIn.mutate` thôi á, nó sẽ viết ra như vầy
```
function onSubmit(data: z.infer<typeof FormSchema>) {
   signIn.mutate(data, {
        onSuccess: () => {},
   })
}```
Nhớ dùng toast của shadcn nha, useToast() í

2024-08-11 04:45 UTC, NganTrucLe commented on src/app/(auth)/log-in/page.tsx
> +                          onClick={() => setShowPassword(!showPassword)}
better code: () => setShowPassword((prev) => !prev)

2024-08-11 04:45 UTC, NganTrucLe commented on src/app/(auth)/reset-password/page.tsx
tương tự

2024-08-11 04:45 UTC, NganTrucLe commented on src/app/(auth)/verify/page.tsx
https://ui.shadcn.com/docs/components/input-otp#form

2024-08-11 04:45 UTC, NganTrucLe commented on src/services/auth.ts
connect API nha, có API rồi á

2024-08-11 04:45 UTC, NganTrucLe commented on src/static-data/provinces.json
ê m cũng bị lỗi cái này, prettier nó ghi đè lên nhma đang sai format json á, t vẫn chưa rõ tại sao lỗi này, m revert changes cái này nha

2024-08-11 15:24 UTC, Huy203 commented on src/app/(auth)/confirm/page.tsx
deleted

2024-08-14 13:49 UTC, NganTrucLe approved these changes

2024-08-14 13:50 UTC, merged